# Generated by Django 5.0.4 on 2024-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Narxi'),
        ),
    ]
