# Generated by Django 5.0.4 on 2024-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hashtags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
