# Generated by Django 5.0.4 on 2024-04-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_products_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='country',
        ),
        migrations.RemoveField(
            model_name='products',
            name='document',
        ),
        migrations.RemoveField(
            model_name='products',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.ManyToManyField(related_name='products', to='db.capacities', verbose_name='Yomkosti')),
                ('color', models.ManyToManyField(related_name='products', to='db.colors', verbose_name='Rangi')),
                ('country', models.ManyToManyField(related_name='products', to='db.countries', verbose_name='Mamlakat')),
                ('document', models.ManyToManyField(related_name='products', to='db.documents', verbose_name='Hujjat')),
                ('memory', models.ManyToManyField(related_name='products', to='db.memories', verbose_name='Xotira')),
                ('price', models.ManyToManyField(related_name='products', to='db.prices', verbose_name='Narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='db.products')),
                ('status', models.ManyToManyField(related_name='products', to='db.statuses', verbose_name='Holati')),
            ],
        ),
    ]
