# Generated by Django 5.0.4 on 2024-04-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_prices_remove_products_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcriteria',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='document',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productcriteria',
            name='status',
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.capacities'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.colors'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.countries'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.documents'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.memories'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.prices'),
        ),
        migrations.AddField(
            model_name='productcriteria',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.statuses'),
        ),
    ]
