# Generated by Django 5.0.4 on 2024-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_productcriteria_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcriteria',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
